import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { Report } from '@/services';

const PERIOD_LABELS: Record<Report['period'], string> = {
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'Last 7 days',
  month: 'Last 30 days',
};

function finalY(doc: jsPDF): number {
  // jspdf-autotable attaches this to the doc instance at runtime — not
  // part of jsPDF's own type, so it's read via a narrow local cast.
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 40;
}

export function downloadReportPdf(report: Report, currentUserName?: string) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const marginX = 14;
  const pageWidth = doc.internal.pageSize.getWidth();
  const isOwn = report.scope === 'own';

  // ── Header ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text('PetroData', marginX, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(isOwn ? 'My Activity Report' : 'System Activity Report', marginX, 25);

  doc.setDrawColor(210, 210, 210);
  doc.line(marginX, 29, pageWidth - marginX, 29);

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  const meta = [
    `Period: ${PERIOD_LABELS[report.period] ?? report.period}`,
    `Scope: ${isOwn ? 'My activity' : 'All users'}`,
    currentUserName ? `Generated by: ${currentUserName}` : null,
    `Generated: ${format(new Date(), 'MMM d, yyyy HH:mm')}`,
  ].filter(Boolean).join('   ·   ');
  doc.text(meta, marginX, 35);

  // ── Summary ─────────────────────────────────────────────────
  let y = 44;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text('Summary', marginX, y);
  y += 6;

  const mostCommonAction = Object.entries(report.by_action_totals)
    .reduce<[string, number] | null>((max, cur) => (!max || cur[1] > max[1] ? cur : max), null);
  const mostActiveUser = report.by_user[0];

  const summaryRows: [string, string][] = [
    ['Total actions', String(report.total_actions)],
    ...(isOwn ? [] : [
      ['Active users', String(report.active_users)] as [string, string],
      ['Most active user', mostActiveUser ? `${mostActiveUser.user_name} (${mostActiveUser.total_actions} actions)` : '—'],
    ]),
    ['Most common action', mostCommonAction ? `${mostCommonAction[0]} (${mostCommonAction[1]} times)` : '—'],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: marginX, right: marginX },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 1.2 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
    body: summaryRows,
  });
  y = finalY(doc) + 8;

  // ── Main data table ─────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(isOwn ? 'By Action' : 'By User', marginX, y);
  y += 4;

  if (isOwn) {
    const rows = Object.entries(report.by_action_totals)
      .sort((a, b) => b[1] - a[1])
      .map(([action, count]) => [action, String(count)]);

    autoTable(doc, {
      startY: y,
      margin: { left: marginX, right: marginX },
      head: [['Action', 'Count']],
      body: rows.length ? rows : [['No activity recorded', '']],
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 9 },
    });
  } else {
    const rows = report.by_user.map(u => [
      `${u.user_name}\n${u.user_email}`,
      String(u.total_actions),
      Object.entries(u.by_action).sort((a, b) => b[1] - a[1]).slice(0, 3).map(([a, c]) => `${a}: ${c}`).join(', '),
      u.first_action_at ? format(new Date(u.first_action_at), 'MMM d, HH:mm') : '—',
      u.last_action_at ? format(new Date(u.last_action_at), 'MMM d, HH:mm') : '—',
    ]);

    autoTable(doc, {
      startY: y,
      margin: { left: marginX, right: marginX },
      head: [['User', 'Total', 'Top actions', 'First', 'Last']],
      body: rows.length ? rows : [['No user activity recorded', '', '', '', '']],
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 8.5 },
      columnStyles: { 0: { cellWidth: 45 } },
    });
  }
  y = finalY(doc) + 8;

  // ── Timeline ────────────────────────────────────────────────
  if (report.timeline.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 18;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Activity Timeline', marginX, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      margin: { left: marginX, right: marginX },
      head: [report.timeline.map(t => t.label)],
      body: [report.timeline.map(t => String(t.count))],
      styles: { fontSize: 7.5, halign: 'center' },
      headStyles: { fillColor: [30, 41, 59] },
    });
  }

  const filename = `petrodata-${isOwn ? 'my' : 'all'}-report-${report.period}-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(filename);
}
